In [ ]:
Why numpy?
-memory
-functionality
-performance

In [2]:
import numpy as np
import sys
#declaring a list of 10 elements
s=[0,1,2,3,4,5,6,7,8,9]
print("size of each element of list in bytes:",sys.getsizeof(s))
print("size of the whole list in bytes:",sys.getsizeof(s)*len(s))

size of each element of list in bytes: 136
size of the whole list in bytes: 1360


In [3]:
#declaring a numpy array of 10 elements
d=np.array([0,1,2,3,4,5,6,7,8,9])
print("size of each element of the numpy array in bytes:",d.itemsize)
print("size of the whole numpy array in bytes:",d.size*d.itemsize)

size of each element of the numpy array in bytes: 4
size of the whole numpy array in bytes: 40


In [4]:
import numpy as np
import time
#size of arrays and lists
size=10000000

In [5]:
#declaring lists
list1=range(size)
list2=range(size)

In [6]:
#declaring arrays
array1=np.arange(size)
array2=np.arange(size)

In [7]:
#capturing time before the multiplication  of python lists
initialTime=time.time()

In [8]:
#multiplying elements of both the lists and stored in another list
resultantList=[(a * b) for a,b in zip(list1,list2)]

In [9]:
#calculating execution time
print("time taken by list to perform multiplication:",(time.time()-initialTime)*1000,"milliseconds")

time taken by list to perform multiplication: 20496.819734573364 milliseconds


In [10]:
#capturing time before the multiplication  of numpy arrays
initialTime=time.time()

In [11]:
#multiplying elements of both the numpy arrays and stored in another numpy array
resultantArray=array1*array2

In [12]:
#calculating execution time
print("time taken by numpy arrays to perform multiplication:",(time.time()-initialTime)*1000,"milliseconds")

time taken by numpy arrays to perform multiplication: 24625.741004943848 milliseconds


In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.random.random(3)

array([0.62928058, 0.78218523, 0.00512871])

In [16]:
np.random.random(4)

array([0.06978726, 0.13685424, 0.59902628, 0.36070516])

In [17]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [18]:
#Indexcing and slicing

In [19]:
data=(1,2,3)


In [20]:
data[0]

1

In [21]:
data[1]

2

In [22]:
data[0:2]

(1, 2)

In [23]:
data[1:]

(2, 3)

In [24]:
data=np.array([[1,2],
              [3,4],
            [5,6]])


In [25]:
data[0,1]

2

In [26]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [27]:
data[0:2,0]

array([1, 3])

In [28]:
data[2,1]

6

In [29]:
data[1:3,1]

array([4, 6])

In [30]:
data[0,0]

1

In [31]:
data[1,1]

4

In [32]:
#slicing 3d array
a=np.array([[[1,2],[3,4],[5,6]],
           [[7,8],[9,10],[11,12]],
           [[13,14],[15,16],[17,18]]])
print(a)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


In [33]:
print(a[0:2])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [34]:
print(a[0:2,1:])

[[[ 3  4]
  [ 5  6]]

 [[ 9 10]
  [11 12]]]


In [35]:
print(a[0:2,1:,1:])

[[[ 4]
  [ 6]]

 [[10]
  [12]]]
